CREATE DATABASE Carros;

USE Carros;

CREATE TABLE Empresa(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	RazaoSocial VARCHAR(100) NOT NULL,
	Endereco VARCHAR(100) NOT NULL
);

CREATE TABLE Marca(
	IdMarca INT PRIMARY KEY IDENTITY,
	NomeMarca VARCHAR(30)
);

CREATE TABLE Modelo(
	IdModelo INT PRIMARY KEY IDENTITY,
	Modelo VARCHAR(50) NOT NULL,
	Ano DATE,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca)
);

CREATE TABLE  Carros(
	IdCarro INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL,
	Placa CHAR(7) NOT NULL,
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo)
); 

CREATE TABLE Cliente(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100) NOT NULL,
	Telefone VARCHAR(12) NOT NULL,
	Cpf VARCHAR(11) NOT NULL,
	NumeroHabilitacao VARCHAR(20) NOT NULL,
	Endereco VARCHAR(50) NOT NULL  
);

CREATE TABLE Aluguel(
	IdAluguel INT PRIMARY KEY IDENTITY,
	Dia DATE NOT NULL,
	Descricao VARCHAR(200),
	Devolucao DATE,
	Valor DECIMAL
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente)
	IdCarro INT FOREIGN KEY REFERENCES Carros(IdCarro)
);

SELECT * FROM Empresa;
SELECT * FROM Marca;
SELECT * FROM Modelo;
SELECT * FROM Carros;
SELECT * FROM Cliente;
SELECT * FROM Aluguel;



