--CRIAR BANCO DE DADOS
CREATE DATABASE Pessoas_Tarde;

--USAR BANCO DE DADOS
USE Pessoas_Tarde;

--CRIAR TABELAS

CREATE TABLE Pessoa(
	IdPessoa INT PRIMARY KEY IDENTITY,
	Nome  VARCHAR(100) NOT NULL,
);
CREATE TABLE Email(
	IdEmail INT PRIMARY KEY IDENTITY,
	Email VARCHAR(100) NOT NULL UNIQUE,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa)

);

CREATE TABLE Telefone(
	IdTelefone INT PRIMARY KEY IDENTITY,
	Telefone VARCHAR(100) NOT NULL UNIQUE,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa)
);

CREATE TABLE CNH(
	IdCNH INT PRIMARY KEY IDENTITY,
	CNH VARCHAR(100) NOT NULL UNIQUE,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa)
);

DROP DATABASE Pessoas_Tarde;
